// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0_RQcE9maGWo-T7B_99Cd9eRk0lW9d5k',
    appId: '1:967064516173:web:4ade2ac6759111347b0e04',
    messagingSenderId: '967064516173',
    projectId: 'reviveecotech-dfbed',
    authDomain: 'reviveecotech-dfbed.firebaseapp.com',
    storageBucket: 'reviveecotech-dfbed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYQyp01LyjwyINBM_UyUy2hoKSw9qYuzA',
    appId: '1:967064516173:android:21dffa95ea00f8227b0e04',
    messagingSenderId: '967064516173',
    projectId: 'reviveecotech-dfbed',
    storageBucket: 'reviveecotech-dfbed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChFe5zJ-mgv0WiLK0Fp6wctJZ7vAPkWUM',
    appId: '1:967064516173:ios:9ef37c20297c58a97b0e04',
    messagingSenderId: '967064516173',
    projectId: 'reviveecotech-dfbed',
    storageBucket: 'reviveecotech-dfbed.firebasestorage.app',
    androidClientId: '967064516173-4fjk27ea55hjlhm80iu9q22m0fpbjmlg.apps.googleusercontent.com',
    iosClientId: '967064516173-4mrjufdpve21afs9silga4scsi62lvlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviveecotechRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChFe5zJ-mgv0WiLK0Fp6wctJZ7vAPkWUM',
    appId: '1:967064516173:ios:9ef37c20297c58a97b0e04',
    messagingSenderId: '967064516173',
    projectId: 'reviveecotech-dfbed',
    storageBucket: 'reviveecotech-dfbed.firebasestorage.app',
    androidClientId: '967064516173-4fjk27ea55hjlhm80iu9q22m0fpbjmlg.apps.googleusercontent.com',
    iosClientId: '967064516173-4mrjufdpve21afs9silga4scsi62lvlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviveecotechRider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuSMF68e_iuYOIfIYwVuz3D1iNEXUQ_MI',
    appId: '1:967064516173:web:b08811a0109f38767b0e04',
    messagingSenderId: '967064516173',
    projectId: 'reviveecotech-dfbed',
    authDomain: 'reviveecotech-dfbed.firebaseapp.com',
    storageBucket: 'reviveecotech-dfbed.firebasestorage.app',
  );
}
